# Generated by Django 2.0.7 on 2018-07-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180724_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_time',
            new_name='created_time',
        ),
    ]
