# Generated by Django 2.0.7 on 2018-07-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180725_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=255, verbose_name='邮箱')),
                ('message', models.TextField(verbose_name='评论内容')),
            ],
            options={
                'verbose_name': '联系',
                'verbose_name_plural': '联系',
            },
        ),
    ]
